### ISSUE TITLE
How to run Server?

### ISSUE THREAD

**Issue by sneakers-the-rat** [WinterLab-Berlin/LabNet#2]
Hello again! Trying to run the performance tests in the examples folder, and I can't figure out how to start the server that it connects to? I see that the test code connects to some local IP ( https://github.com/WinterLab-Berlin/LabNet/blob/34e71c6827d2feef9b65d037ee5f2e8ca227db39/examples/python/perf_test/test.py#L10 ) but I can't quite figure out how to start that process! Thanks in advance :)

**Comment by darki-31** [comment]
Actually LabNet is the server and the test run as client. Here is a short description of how to start the Python test client.

The best way is first to create a virtual environment 
```
py -m venv venv
```
activate it with
```
.\venv\Scripts\Activate.ps1
```
if you on Windows with Powershell. On Linux it's very similar.

Install all python requirements from “requirements.txt”
```
pip install -r requirements.txt
```
Now change the IP address in “test.py” to the address of your RaspberryPi and run the test with “python test.py”.  Also, don't forget to start LabNet on the RasPi before.
For the third test you need to connect pins 5 and 23 (WiringPi notation). Otherwise it fails.
